### ISSUE TITLE
One Definition Rule and Details Headers

### ISSUE THREAD

**Issue by Jmeyer1292** [lovepark/ifm3d#107]
In the case of the `opencv` module (and perhaps others) the implementation of member functions of `OpenCVBuffer` are provided in an included header file.

This means that if any of the opencv-module headers are included in more than one translational unit across a program, you'll end of with compiler definitions complaining about multiple definitions.

Please consider marking all functions in "implementation" header files as `inline`.

**Comment by tpanzarella** [comment]
Fixed in 0.11.1
