### ISSUE TITLE
Windows, cmake issue with PCL or boost

### ISSUE THREAD

**Issue by pfrydlewicz** [lovepark/ifm3d#21]
Hello,

when configuring cmake under windows, I get the problem below.
I downloaded PCL version 1.7.2 as source code and pointed to ...\pcl-1.7.2\cmake as PCL_DIR.
Looking into the PCL folder, there is only a pcl_pclconfig.cmake file.

Where can I fix this?

- For now I only need the camera module, thus no need for PCL. However when switching off all modules this error still persists.

- Also, there is the BoostConfig.cmake file that is mentioned in the cmake error log with a static PCL folder as entry:
include("C:/Projets/PCL/SuperBuild_boost_1_50/CMakeExternal/Install/Boost/share/boost-${Boost_VERSION}/cmake/BoostConfig.cmake")

The boost (1.50.0) and PCL (1.7.2) directories are set appropriatly.

Thanks for help.

Here the cmake error message:
--------------------------------------------------------------------------------------------------

CMake Error at D:/Tools/Boost/share/cmake/boost/BoostConfig.cmake:15 (include):
  include could not find load file:

    C:/Projets/PCL/SuperBuild_boost_1_50/CMakeExternal/Install/Boost/share/boost-/cmake/BoostConfig.cmake
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:236 (find_package)
  modules/camera/CMakeLists.txt:19 (find_package)

Boost  found.
globbed: 
CMake Error at D:/Tools/Boost/share/cmake/boost/BoostConfig.cmake:15 (include):
  include could not find load file:

    C:/Projets/PCL/SuperBuild_boost_1_50/CMakeExternal/Install/Boost/share/boost-/cmake/BoostConfig.cmake
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:236 (find_package)
  modules/framegrabber/CMakeLists.txt:12 (find_package)

Boost  found.
Found Boost components:
   system
globbed: 
CMake Error at D:/Tools/Boost/share/cmake/boost/BoostConfig.cmake:15 (include):
  include could not find load file:

    C:/Projets/PCL/SuperBuild_boost_1_50/CMakeExternal/Install/Boost/share/boost-/cmake/BoostConfig.cmake
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:236 (find_package)
  modules/framegrabber/src/libifm3d_framegrabber/CMakeLists.txt:1 (find_package)

Boost  found.
Found Boost components:
   system;date_time;regex

**Comment by graugans** [comment]
@pfrydlewicz thanks for testing this feature. I am sorry but the image module is still missing in the windows port. This is due to the fact that the PCL and OpenCV are big beasts and there are no pre compiled versions for all Visual Studio versions available. For me it was important to have step one before step two and the first step was the integration of the basic feature set. In step two what we are currently working on we try to provide as much information as possible to handle OpenCV and PCL. Meanwhile a solution could be to use the provided image module and strip down the image module to not use OpenCV and PCL. I guess this will do the trick for most of the windows users.

Of course you can add this reduced image module in your own project. You only need to derive from [ifm3d::ByteBuffer](https://github.com/lovepark/ifm3d/blob/master/modules/image/include/ifm3d/image/image_buffer.h#L40) I guess an simple_image module just putting out the image data as ``std::vector`` or ``std::array`` should be no big deal. If you have the time to strip down and write some test cases I guess @tpanzarella will merge this.

**Comment by tpanzarella** [comment]
@pfrydlewicz We do have plans to create additional modules that will project the pixel data into alternate data structures. Some of which are header-only libraries like [Eigen](http://eigen.tuxfamily.org) and [xtensor](https://github.com/QuantStack/xtensor). This should make the build issues much simpler. I do not have a specific time frame for you except to say that it is coming *soon*.

**Comment by Arag24** [comment]
@tpanzarella Would be really happy to get this module splitting. Great added value for Windows user; to my prospective.

**Comment by graugans** [comment]
Here is a first draft version of the image module build instructions on Windows. I've not yet tested it myself.

```patch
From 0a1d46c453e60cf5f000a6fecbb81f4d49679c26 Mon Sep 17 00:00:00 2001
From: Marco Kirchner <Marco.Kirchner@ifm.com>
Date: Thu, 18 Jan 2018 16:42:47 +0100
Subject: [PATCH] add initial support for image module on windows

---
 doc/windows.md                                     | 101 ++++++++++++++++++---
 .../framegrabber/include/ifm3d/fg/byte_buffer.h    |  15 ++-
 .../src/libifm3d_framegrabber/byte_buffer.cpp      |   3 +-
 modules/image/src/libifm3d_image/CMakeLists.txt    |  13 ++-
 modules/tools/src/libifm3d_tools/CMakeLists.txt    |   6 +-
 5 files changed, 115 insertions(+), 23 deletions(-)

diff --git a/doc/windows.md b/doc/windows.md
index 45325fa..c37813a 100644
--- a/doc/windows.md
+++ b/doc/windows.md
@@ -1,22 +1,28 @@
 # How to build ifm3d library from source on Windows.
 
-As a first step we build ifm3d without the image module.
-
 ## Prepare dependent tools
 
-Make sure that you have installed CMake and VS2017 64bit before you move to the next step.
+Make sure that you have installed CMake and Visual Studio 64bit before you move to the next step.
 
 * [CMake v3.9.1](http://www.cmake.org)
 * [Visual Studio Community 2017](https://www.visualstudio.com)
 * [Git for Windows](https://git-for-windows.github.io/) or any git client
 
+Note: Visual Studio 2015 or later is required as older versions don't support all required features of C++11
+
 ## Download dependencies
 
-Start with downloading Glog, curl and XMLRPC libraries from repository listed below.
+Start with downloading the libraries from repositories listed below.
 
 * [Glog](https://github.com/google/glog)
 * [xmlrpc-c](https://github.com/graugans/xmlrpc-c)
 * [curl](https://github.com/curl/curl)
+* [Eigen](https://github.com/eigenteam/eigen-git-mirror)
+* [FLANN](https://github.com/mariusmuja/flann)
+* [VTK](https://gitlab.kitware.com/vtk/vtk)
+* [PCL](https://github.com/PointCloudLibrary/pcl)
+
+
 
 For all the download operations, the command line is a msys git bash. All operations are relative to each project top folder. 
 
@@ -44,6 +50,36 @@ $ git clone https://github.com/curl/curl.git
 $ git checkout -b curl-7_47_1 curl-7_47_1
 ```
 
+### Download FLANN
+```
+$ git clone https://github.com/mariusmuja/flann.git
+$ git checkout -b 1.9.1 1.9.1
+```
+
+### Download Eigen
+```
+$ git clone https://github.com/eigenteam/eigen-git-mirror.git
+$ git checkout -b 3.3.4 3.3.4
+```
+
+### Download VTK
+```
+$ git clone https://gitlab.kitware.com/vtk/vtk.git
+$ git checkout -b v6.3.0 -v6.3.0
+```
+
+### Download PCL
+```
+$ git clone https://github.com/PointCloudLibrary/pcl.git
+$ git checkout -b pcl-1.8.1 pcl-1.8.1
+```
+
+### Download OpenCV
+```
+$ git clone https://github.com/opencv/opencv.git
+$ git checkout -b 3.4.0 3.4.0
+```
+
 ## Build the 3rdParty Libraries
 
 The following command line examples assume we run from a windows command prompt with CMake in the Path variable.
@@ -60,6 +96,8 @@ set PATH=%PROGRAMFILES%\CMake\bin;%PATH%
 set PATH=%PROGRAMFILES(x86)%\CMake\bin;%PATH%
 ```
 
+All the dependencies will by default get installed into "C:\ifm3d-deps\" please make sure you have write access to this folder or change the paths accordingly.
+
 ### Building curl
 
 To build the curl library it is recommended to use CMake for setting the arch to x64.
@@ -67,10 +105,9 @@ To build the curl library it is recommended to use CMake for setting the arch to
 ```
 > mkdir build
 > cd build
-> cmake -Ax64  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ..
+> cmake -Ax64  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/curl ..
 > cmake --build . --clean-first --config Release --target INSTALL
 ```
-After a successful curl build the build artifacts will be for example found in ``%PROGRAMFILES(x86)%\CURL``. Please double check this with your configuration and platform.
 
 
 ### Building glog
@@ -80,7 +117,49 @@ Follow the build instructions in ``cmake/INSTALL.md`` for more details.
 ```
 > mkdir build
 > cd build
-> cmake -A x64 ..
+> cmake -A x64 -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/glog ..
+> cmake --build . --clean-first --config Release --target INSTALL
+```
+
+
+### Building FLANN
+```
+> mkdir build
+> cd build
+> cmake -A x64 -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_MATLAB_BINDINGS=OFF  -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/flann ..
+> cmake --build . --clean-first --config Release --target INSTALL
+```
+
+
+### Building Eigen
+```
+> mkdir build
+> cd build
+> cmake -A x64  -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/eigen ..
+> cmake --build . --clean-first --config Release --target INSTALL
+```
+
+### Building VTK
+```
+> mkdir build
+> cd build
+> cmake -A x64 -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/vtk ..
+> cmake --build . --clean-first --config Release --target INSTALL
+```
+
+### Building PCL
+```
+> mkdir build
+> cd build
+> cmake -A x64 DPCL_ENABLE_SSE=OFF -DWITH_CUDA=OFF -DWITH_DAVIDSDK=OFF -DWITH_DOCS=OFF -DWITH_DSSDK=OFF -DWITH_ENSENSO=OFF -DWITH_FZAPI=OFF -DWITH_LIBUSB=OFF -DWITH_OPENGL=ON -DWITH_OPENNI=OFF -DWITH_OPENNI2=OFF -DWITH_PCAP=OFF -DWITH_PNG=OFF -DWITH_QHULL=OFF -DWITH_QT=OFF -DWITH_RSSDK=OFF  -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/pcl ..
+> cmake --build . --clean-first --config Release --target INSTALL
+```
+
+### Building OpenCV
+```
+> mkdir build_cmake
+> cd build_cmake
+> cmake -A x64 -DWITH_CUDA=OFF -DWITH_EIGEN=ON -DWITH_IPP=ON -DWITH_JASPTER=ON -DWITH_JPEG=ON -DWITH_OPENEXR=OFF -DWITH_OPENNI=OFF -DWITH_PNG=ON -DWITH_QT=OFF -DWITH_QT_OPENGL=OFF -DWITH_TBB=OFF -DWITH_TIFF_ON -DWITH_VIDEOINPUT=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_PACKAGE=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_openvc_python=OFF -DCMAKE_INSTALL_PREFIX=C:/ifm3d-deps/opencv ..
 > cmake --build . --clean-first --config Release --target INSTALL
 ```
 
@@ -92,15 +171,10 @@ Install the necessary libraries on your system.
 * [Boost v1.64.0](http://www.boost.org) Download [link](https://dl.bintray.com/boostorg/release/1.64.0/binaries/) to version 1.64 for Visual Studio 2017 (MSVC 14.1)
 
 ## Build the project via CMake.
-
-Due to the fact there are no default locations under Windows for include files and libraries we have to provide CMake some hints.
-
 ```
 > mkdir build
 > cd build
-> :: The CMAKE_PREFIX_PATH depends on the location you previously installed CURL to
-> set CMAKE_PREFIX_PATH=%PROGRAMFILES(x86)%\CURL
-> cmake -Ax64  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DBUILD_SDK_PKG=OFF -DBUILD_TESTS=OFF -DBUILD_MODULE_IMAGE=OFF -DBUILD_MODULE_EXAMPLES=OFF -DBoost_INCLUDE_DIR="D:\local\boost_1_64_0" -DBOOST_LIBRARYDIR=D:\local\boost_1_64_0\lib64-msvc-14.1 -DBoost_COMPILER=-vc141 -DBoost_USE_STATIC_LIBS=ON  -DCMAKE_BUILD_TYPE=Release ..
+> cmake -Ax64  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DBUILD_SDK_PKG=OFF -DBUILD_TESTS=OFF -DBUILD_MODULE_EXAMPLES=OFF -DCMAKE_PREFIX_PATH="C:/ifm3d-deps/curl" -DBoost_INCLUDE_DIR="C:/ifm3d-deps/boost_1_64_0" -DBOOST_LIBRARYDIR="C:/ifm3d-deps/boost_1_64_0/lib64-msvc-14.1" -DBoost_COMPILER=-vc141 -DBoost_USE_STATIC_LIBS=ON -DEIGEN_INCLUDE_DIR="C:/ifm3d-deps/eigen/include/eigen3" -DCMAKE_BUILD_TYPE=Release ..
 > cmake --build . --clean-first --config Release --target INSTALL
 ```
 
@@ -116,6 +190,5 @@ ifm3d: version=0.3.2
 
 # TODO list
 
-- [ ] Update the documentation to include the ``image`` module
 - [ ] Fix the CMake installation routines. On Windows not all artifacts are installed. For example the headers are missing
 - [ ] Provide better support for xml-rpc
diff --git a/modules/framegrabber/include/ifm3d/fg/byte_buffer.h b/modules/framegrabber/include/ifm3d/fg/byte_buffer.h
index 698de03..591cc52 100644
--- a/modules/framegrabber/include/ifm3d/fg/byte_buffer.h
+++ b/modules/framegrabber/include/ifm3d/fg/byte_buffer.h
@@ -24,10 +24,19 @@
 #include <memory>
 #include <vector>
 
+// Annoying stuff for windows -- makes sure clients can import these functions
+#ifndef IFM3D_DLL_DECL
+# if defined(_WIN32) && !defined(__CYGWIN__)
+#   define IFM3D_DLL_DECL  __declspec(dllimport)
+# else
+#   define IFM3D_DLL_DECL
+# endif
+#endif
+
 namespace ifm3d
 {
-  extern const std::size_t IMG_TICKET_SZ; // bytes
-  extern const std::size_t IMG_BUFF_START; // byte number
+  extern IFM3D_DLL_DECL const std::size_t IMG_TICKET_SZ; // bytes
+  extern IFM3D_DLL_DECL const std::size_t IMG_BUFF_START; // byte number
 
   enum class pixel_format : std::uint32_t
   {
@@ -132,7 +141,7 @@ namespace ifm3d
       unsigned char bytes[sizeof(T)];
     } value;
 
-#if __BYTE_ORDER == __BIG_ENDIAN
+#if !defined(_WIN32) && __BYTE_ORDER == __BIG_ENDIAN
     std::reverse_copy(buff, buff + sizeof(T), value.bytes);
 #else
     std::copy(buff, buff + sizeof(T), value.bytes);
diff --git a/modules/framegrabber/src/libifm3d_framegrabber/byte_buffer.cpp b/modules/framegrabber/src/libifm3d_framegrabber/byte_buffer.cpp
index 28bcf6a..6980341 100644
--- a/modules/framegrabber/src/libifm3d_framegrabber/byte_buffer.cpp
+++ b/modules/framegrabber/src/libifm3d_framegrabber/byte_buffer.cpp
@@ -64,8 +64,9 @@ ifm3d::get_chunk_index(const std::vector<std::uint8_t>& buff,
                        std::size_t start_idx)
 {
   std::size_t idx = start_idx; // start of first chunk
+  std::size_t size = buff.size()-6;
 
-  while ((buff.begin()+idx) < (buff.end()-6))
+  while (idx < size)
     {
       if (static_cast<std::uint32_t>(chunk_type) ==
           ifm3d::mkval<std::uint32_t>(buff.data()+idx))
diff --git a/modules/image/src/libifm3d_image/CMakeLists.txt b/modules/image/src/libifm3d_image/CMakeLists.txt
index 47e3153..d5aa3c4 100644
--- a/modules/image/src/libifm3d_image/CMakeLists.txt
+++ b/modules/image/src/libifm3d_image/CMakeLists.txt
@@ -1,13 +1,18 @@
-find_library(LIB_glog NAMES glog)
+find_package(Boost REQUIRED COMPONENTS system date_time regex)
+find_package(glog QUIET CONFIG NAMES google-glog glog)
+if (NOT TARGET glog::glog)
+	find_library(LIB_glog NAMES glog)
+else()
+	set(LIB_glog glog::glog)
+endif (NOT TARGET glog::glog)
 
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
 
 file(GLOB IFM3D_IMAGE_SOURCES *.cpp)
-add_library(ifm3d_image OBJECT ${IFM3D_IMAGE_SOURCES})
-set_property(TARGET ifm3d_image PROPERTY POSITION_INDEPENDENT_CODE 1)
 
 add_library(
-  ifm3d_image_shared SHARED $<TARGET_OBJECTS:ifm3d_image>)
+  ifm3d_image_shared SHARED ${IFM3D_IMAGE_SOURCES})
+set_property(TARGET ifm3d_image_shared PROPERTY POSITION_INDEPENDENT_CODE 1)
 
 target_link_libraries(
   ifm3d_image_shared
diff --git a/modules/tools/src/libifm3d_tools/CMakeLists.txt b/modules/tools/src/libifm3d_tools/CMakeLists.txt
index 629fe4e..a5a0d92 100644
--- a/modules/tools/src/libifm3d_tools/CMakeLists.txt
+++ b/modules/tools/src/libifm3d_tools/CMakeLists.txt
@@ -55,8 +55,12 @@ if (BUILD_MODULE_IMAGE)
     )
   set_target_properties(ifm3d_tools_shared PROPERTIES
     AUTOMOC TRUE
-    COMPILE_FLAGS "-Wno-deprecated -Wno-deprecated-declarations"
     )
+  if(NOT WIN32)
+    set_target_properties(ifm3d_tools_shared PROPERTIES
+      COMPILE_FLAGS "-Wno-deprecated -Wno-deprecated-declarations"
+      )
+  endif()
 else()
   set_target_properties(ifm3d_tools_shared PROPERTIES
     VERSION ${IFM3D_VERSION_STRING}
-- 
2.7.4
```

**Comment by pfrydlewicz** [comment]
Thanks for the commitment to do a windows version.

**Comment by GMSLLB** [comment]
Hello,
when configuring cmake of pcl under windows, I get the problem below.
-- Configuring incomplete, errors occurred!
See also "D:/%IFM3D_BUILD_DIR%/pcl/build/CMakeFiles/CMakeOutput.log".
See also "D:/%IFM3D_BUILD_DIR%/pcl/build/CMakeFiles/CMakeError.log".

I looked into the file CMakeError.log, it explained this:
D:\%IFM3D_BUILD_DIR%\pcl\build\CMakeFiles\CMakeTmp\src.cxx(2):fatal error
C1083: Unable to open the include file: "mm_malloc.h": No such file or directory.

How can I fix this?

Thanks for help!

**Comment by Arag24** [comment]
@GMSLLB, could you please open a new Thread on this just for clarity please ? 
It looks like more a problem with  PCL building. What is version of PCL? We can propose also propose you Win x64 binaries with PCL build if preferred.
Just open new thread, please.

**Comment by GMSLLB** [comment]
> @GMSLLB, could you please open a new Thread on this just for clarity please ?
> It looks like more a problem with PCL building. What is version of PCL? We can propose also propose you Win x64 binaries with PCL build if preferred.
> Just open new thread, please.

@Arag24 , the version of PCL is 1.8.1 from pcl-1.8.1 https://github.com/PointCloudLibrary/pcl.git; and I built PCL with Win x64. 
Now, it always exited that:
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindBoost.cmake:2064 <message>:
  Unable to find the requested Boost libraries.
  Unable to find the Boost header files. Please set BOOST_ROOT to the root directory containing Boost or     
  BOOST_INCLUDEDIR to the directory containing Boost's headers.
Call Stack <most recent call first>:
   cmake/pcl_find_boost.cmake:43 <find_package>
   CMakeLists.txt:418 <include>

**Comment by graugans** [comment]
@GMSLLB please open a new issue with the exact Visual Studio Version you are currently using. The Windows version and if you are running a 64Bit or 32Bit version of Windows. Another thing which might make things struggle is that on Windows 10 some set-ups default to the powershell and not the old cmdline.
