### ISSUE TITLE
Implement PCIC Client as a PIMPL

### ISSUE THREAD

**Issue by tpanzarella** [lovepark/ifm3d#50]
The current `pcicclient` module exposes unnecessary information in its public headers which causes steeper than necessary dependencies on users of the library and also makes expressing usage of the `pcicclient` in an external project unnecessarily verbose. Specifically, all of the Boost related dependencies, which are declared `private` in the PCIC client interface class should move to a pimpl. The `camera` and `framegrabber` modules would be good models to follow.

**Comment by graugans** [comment]
The syntron team is currently working on this. There will be a PR against dev-0.9.0 soon.

**Comment by tpanzarella** [comment]
This has been merged via #60
