### ISSUE TITLE
Missing debian package dependencie

### ISSUE THREAD

**Issue by aslakjo** [lovepark/ifm3d#6]
Hi

We are trying to setup a minimal environment to use the PCL-python bindings with the o3d3 camera. However when we install the *.deb packages from the 0.1.0 release. We get the following error.

```
 ifm3d-image depends on ros-kinetic-opencv3; however:
  Package ros-kinetic-opencv3 is not installed.

```

Can you help us find the missing package? Or is there other workarounds to accomplish this?

Best regards Aslak Os, Rocketfarm

**Comment by tpanzarella** [comment]
Hi Aslak,

I would suggest building the latest release from source. This will also build a deb (if you wish) and will introspect your system with the proper OpenCV dependency. 

The binary debs from 0.1.0 were there simply to accommodate very early adopter companies using the O3X. The expressed dependency that you are lacking is the OpenCV 3 package bundled with ROS Kinetic. If you build from source, that particular deb is not required. 

I hope this helps. 

Tom Panzarella
Founder & CEO
Love Park Robotics, LLC
2025 Washington Ave, Suite 217
Philadelphia, PA 19146 USA

mobile: +1 215 341 1754
tom@loveparkrobotics.com
http://loveparkrobotics.com

**Comment by aslakjo** [comment]
Thanks for the quick reply, ill try that out.
