### ISSUE TITLE
Remove requirement for Boost regex and date_time

### ISSUE THREAD

**Issue by tpanzarella** [lovepark/ifm3d#65]
In 0.9.0 we are moving to C++14. It would be good to investigate if, given the more modern standard, we can get rid of the `pcicclient` mdoule's use of Boost regex and date_time. @graugans

**Comment by graugans** [comment]
@tpanzarella when switching to full C++14 we have no chance to get the OEM module for ifm3d within a long period of time.

**Comment by tpanzarella** [comment]
I don't understand. Why?

**Comment by graugans** [comment]
I see no chance in updating the gcc and CMake the toolchain for the camera within the next year.
