### ISSUE TITLE
Max FPS

### ISSUE THREAD

**Issue by nayan27** [lovepark/ifm3d#72]
Hi there,

Using a O3D303 in low exposure type without temporal or spatial filter, with the continuous acquisition mode. In ifmAssistant, i get a framerate of 8-9.

But using a basic program based on the ifm3d library, i only get exactly 1 fps. Am i missing something ?

![image](https://user-images.githubusercontent.com/6426330/40933757-777a6574-6800-11e8-9bd7-bedadce39791.png)

**Comment by graugans** [comment]
Could you please be so kind and specify the software versions (ifm3d, firmware, Vision Assitant) you are using?

You can verify your results by using the ``ifm3d hz`` tool.

**Comment by nayan27** [comment]
After looking at the ifm3d hz tool as you mentionned, i noticed that using the ByteBuffer instead of the ImageBuffer seems to solve the problem and FPS are now coming in way faster. Any idea on why ImageBuffer is slower ?

**Comment by tpanzarella** [comment]
Please attach the full output of `ifm3d dump` so that we can reproduce your configuration and provide some insights into your issue.

**Comment by nayan27** [comment]
Hi simply to let you know that using ByteBuffer did get rid of the delay problem and that it suits our application for now ! I believe you can close this issue if you wish ! Thanks
