### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by Postea-CS** [lovepark/ifm3d#90]
Is there a way to do static build?

**Comment by tpanzarella** [comment]
We currently do not have the struts in place to perform a static build.

**Comment by Postea-CS** [comment]
How about using another version of boost? One that I build myself. tried export BOOST_ROOT but still isn't finding -lBoost:system.

**Comment by tpanzarella** [comment]
We use CMake as our meta-build system. To that end, we employ Boost's integration with CMake to locate our Boost related dependencies *and* to properly set our compiler and linker flags. So, for example, in our `framegrabber` module where we rely on ASIO (header-only ... so nothing to link to) and System, we specify that dependency like: `find_package(Boost REQUIRED COMPONENTS system)`. What this amounts to in terms of linking is that we specify `-lboost_system` (not as you spell it above). Similarly, in our `tools` module, we utilize Boost program options (for parsing command-line arguments), which we call out as `find_package(Boost REQUIRED COMPONENTS program_options)` and manifests as a linker specification like `-lboost_program_options`.

If your custom Boost build does not include the CMake integration (i.e., acquiring compiler/linker settings via `find_package(...)`, you could edit our CMakeList.txt files as necessary to explicitly link to the libraries you installed. I could try to provide some guidance on that if necessary.
