### ISSUE TITLE
Changing the vewing angle?

### ISSUE THREAD

**Issue by Semih67** [lovepark/ifm3d#99]
Is it possible to tune the camera in that way that it has a greater viewing angle? I have looked in the ifm3d dump but couldn't find anything.

**Comment by graugans** [comment]
@Semih67 the viewing angle is related on the lens built into your camera. Which model do you own?

**Comment by Semih67** [comment]
O3X100

**Comment by graugans** [comment]
In this case there is no model with wider opening angle. You can only use multiple O3X to have a wider field of view.

**Comment by Semih67** [comment]
Ok, thank you
